### ISSUE TITLE
Implement UI background graphics for whole screen and/or special screen areas

### ISSUE THREAD

**Issue by youngneil1** [IceBlinkEngine/IB2Engine#17]
All optional via module property (bool useUIBackground):

Satrted with main screen and working on:
UIBackgroundPortraits
UIBackgroundArrows
UIBackgroundHotkeys
UIBackgroundToggles
UIBackgroundLog

Other screens than main screen so far just use one background image (instead of black), migth get more sophisticated later.

Guess I am halway through with figuring out dynamic dimensions of the Bbackgroudn UI draw dst rects right now.

Ideally I would like to use some background graphics that have structure at their border, like a wall, fence, ornaments...

**Comment by youngneil1** [comment]
Cool work in the last two commits in this area! I lost a bit of my own fumbling work due to making some mistakes while trying to combine the changed versions of the very same files (remote and local) in VS 2015, brrr.

I think best to do for me is to focus on another area of developing/module building for the time being and later on once the smoke has settled return to this field (if necessary at all afterwards anymore, looks perfectly spot on as it develops).

Just give me a heads once your done setting up the stage for the various draw methods across all screens :-).

**Comment by slowdive-fan** [comment]
Sounds great, I'm trying to make it so that most of the code is the exact same on both PC and android with any unique code being in separate methods (mostly drawing stuff and html text format handling...android automatically handles it, but I had to create our own for the PC). I think we are pretty good with the features in lace to have an initial release, I just want to do some more code cleaning (old class and methods and commented out stuff still siting around) and fine tune all the UI layout for all resolutions and devices.
